### ISSUE TITLE
Baseline needs to be updated. 

### ISSUE THREAD

**Issue by noha** [pharo-contributions/ImageWorker#4]
Referenced software in the baseline of Imageworker point to very ancient repos

**Comment by tinchodias** [comment]
Note: The baseline defines #osProcess: but it's not sent.

**Comment by tinchodias** [comment]
I did some clean up so this issue refers only to:

~~~Smalltalk
BaselineOfImageWorker >> commandShell: spec [
	spec project: 'CommandShell' with: [
		spec
			repository: 'http://www.squeaksource.com/MetacelloRepository';
			className: 'ConfigurationOfCommandShell';
			version: #stable ].
~~~

OSSubprocess doesn't work on Windows AFAIK so don't know how to update it.
